---
- name: Shorten logrotate periods
  copy:
    dest: "/etc/logrotate.d/rsyslog"
    content: |
      /var/log/syslog
      {
              rotate 0
              daily
              missingok
              notifempty
              delaycompress
              maxsize 8M
              compress
              postrotate
                      /usr/lib/rsyslog/rsyslog-rotate
              endscript
      }
      /var/log/mail.info
      /var/log/mail.warn
      /var/log/mail.err
      /var/log/mail.log
      /var/log/daemon.log
      /var/log/kern.log
      /var/log/auth.log
      /var/log/user.log
      /var/log/lpr.log
      /var/log/cron.log
      /var/log/debug
      /var/log/messages
      {
              rotate 0
              weekly
              missingok
              notifempty
              compress
              delaycompress
              maxsize 5M
              sharedscripts
              postrotate
                      /usr/lib/rsyslog/rsyslog-rotate
              endscript
      }

- name: Add preemptive log removal
  cron:
    name: remove log spam
    job: "rm -rf /var/log/*.1"
    user: root
    cron_file: /etc/crontab
    special_time: hourly
